#!/usr/bin/env python3

from sudoku import HyperSudoku, crange
import sys
import time

def print_red_digit(k):
    return "\033[31m" + str(k) +"\033[0m"

if __name__ == "__main__":

    # each Sudoku hyperSudoku block has m rows and n columns
    (m, n) = map(int, input().split())

    # initialize the hyperSudoku solver
    hyper_sudoku = HyperSudoku(m, n)

    # N = m*n is the number of rows/columns in the hyperSudoku
    N = hyper_sudoku.size()

    # set the initially known values on the hyperSudoku
    for i in crange(1, N):
        row = input().split()
        for j in crange(1, N):
            k = row[j - 1]
            if k.isdigit():
                hyper_sudoku.set_cell_value(i, j, int(k))
                
    start_time = time.time()

    # solve the hyperSudoku
    if not hyper_sudoku.solve():
        sys.stdout.write("HyperSudoku is not valid.\n")
        exit(1)
        
    end_time = time.time()

    # print the solution
    digits = len(str(N))
    pad = lambda k: str(k).rjust(digits)
    
    # Only for 3x3 hyperSudoku puzzles
    if m == 3 and n == 3:
        for i in crange(1, N):
            for j in crange(1, N):
                k = hyper_sudoku.get_cell_value(i, j)
                if (i, j) in [(2, 2), (2, 3), (2, 4), (3, 2), (3, 3), (3, 4), (4, 2), (4, 3), (4, 4),
                              (2, 6), (2, 7), (2, 8), (3, 6), (3, 7), (3, 8), (4, 6), (4, 7), (4, 8),
                              (6, 2), (6, 3), (6, 4), (7, 2), (7, 3), (7, 4), (8, 2), (8, 3), (8, 4),
                              (6, 6), (6, 7), (6, 8), (7, 6), (7, 7), (7, 8), (8, 6), (8, 7), (8, 8)]:
                    sys.stdout.write("\033[31m" + str(k) +"\033[0m" + " ")
                else:
                    sys.stdout.write(pad(k) + " ")
                if j % 3 == 0 and j < N:
                    sys.stdout.write("| ")
            sys.stdout.write("\n")
            if i % 3 == 0 and i < N:
                sys.stdout.write("{}+{}+{}\n".format("-"*6, "-"*7, "-"*6))
    else:
        for i in crange(1, N):
            for j in crange(1, N):
                k = hyper_sudoku.get_cell_value(i, j)
                sys.stdout.write("%s" % pad(k) + (" " if j < N else ""))
            sys.stdout.write("\n")  
        
    # Print the time taken
    print("\nTime elapsed: %.5f sec." % (end_time - start_time))
        
    sys.stdout.write("\n")