#!/usr/bin/env python3

from sudoku import Greater_Than_Sudoku, crange
import sys
import time

def parse_constraints(constraints):
    cons = []
    for constraint in constraints:
        if "gt" in constraint:
            parts = constraint.split("),(")
            i1, j1 = map(int, parts[0][2:].split(','))
            i2, j2 = map(int, parts[1].split(')')[0].split(','))
            cons.append(((i1, j1), (i2, j2)))
    return cons

if __name__ == "__main__":
    # Read only m*n + 1 lines
    m, n = map(int, input().split())
    
    # Read the board
    board = []
    for i in range(m*n):
        row = input().split()
        for j in range(m*n):
            if row[j] in ["_", "0", ".", "*", "?"]:
                row[j] = '_'
            else:
                row[j] = int(row[j])
        board.append(row)
        
    # Get the constraints
    constraints = []
    while True:
        try:
            line = input().strip()
            if line.startswith("[("):
                constraints.append(line)
        except EOFError:
            break
    
    cons = parse_constraints(constraints)
            
    greater_than_puzzle = Greater_Than_Sudoku(m, n, board, cons)
    
    start_time = time.time()
    
    # Solve the puzzle
    if not greater_than_puzzle.solve():
        sys.stdout.write("Greater Than Sudoku puzzle is not valid.\n")
        exit(1)
        
    end_time = time.time()
    
    # Print the solution
    digits = len(str(m*n))
    pad = lambda k: str(k).rjust(digits)
    
    if m == 3 and n == 3:
        for i in crange(1, m*n):
            for j in crange(1, m*n):
                sys.stdout.write(pad(greater_than_puzzle.get_cell_value(i, j)) + " ")
                if j % 3 == 0 and j < m*n:
                    sys.stdout.write("| ")
            sys.stdout.write("\n")
            if i % 3 == 0 and i < m*n:
                sys.stdout.write("{}+{}+{}\n".format("-"*6, "-"*7, "-"*6))
    else:
        for i in crange(1, m*n):
            for j in crange(1, m*n):
                k = greater_than_puzzle.get_cell_value(i, j)
                sys.stdout.write("%s" % pad(k) + (" " if j < m*n else ""))
            sys.stdout.write("\n") 

    # Print the time taken
    print("Time elapsed: %.5f sec." % (end_time - start_time))

    sys.stdout.write("\n")
