#!/usr/bin/env python3

from sudoku import Killer_Sudoku, crange
import sys
import time

if __name__ == "__main__":
    
    # The input before the first "[" is the puzzle and the input after the first "[" are the cages
    input = sys.stdin.read().split("[")

    # Take the n and m values from the puzzle
    n, m = map(int, input[0].split("\n")[0].split())
    
    cages = []
    for cage in input[1:]:
        # add "[" in the beginning of the string
        cage = "[" + cage
        cages.append(eval(cage))

    # Initialize the Killer Sudoku solver
    killer_puzzle = Killer_Sudoku(m, n, cages)

    start_time = time.time()

    # Solve the puzzle
    if not killer_puzzle.solve():
        sys.stdout.write("Killer Sudoku puzzle is not valid.\n")
        exit(1)

    end_time = time.time()

    assignments = 0

    # Print the solution
    digits = len(str(m*n))
    pad = lambda k: str(k).rjust(digits)
    
    if m == 3 and n == 3:
        for i in crange(1, m*n):
            for j in crange(1, m*n):
                sys.stdout.write(pad(killer_puzzle.get_cell_value(i, j)) + " ")
                if j % 3 == 0 and j < m*n:
                    sys.stdout.write("| ")
            sys.stdout.write("\n")
            if i % 3 == 0 and i < m*n:
                sys.stdout.write("{}+{}+{}\n".format("-"*6, "-"*7, "-"*6))
    else:
        for i in crange(1, m*n):
            for j in crange(1, m*n):
                k = killer_puzzle.get_cell_value(i, j)
                sys.stdout.write("%s" % pad(k) + (" " if j < m*n else ""))
            sys.stdout.write("\n") 

    # Print the time taken
    print("\nTime elapsed: %.5f sec." % (end_time - start_time))

    sys.stdout.write("\n")